# Generated by Django 4.1.6 on 2023-02-18 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MS_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField()),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('review_on', models.DateField()),
                ('revision', models.IntegerField()),
                ('clause_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MS.ms_menu')),
                ('document_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pro_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('review_on', models.DateField()),
                ('revision', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('details', models.TextField()),
                ('procedure_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MS.procedure')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
