# Generated by Django 4.1.6 on 2023-02-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0002_alter_ms_menu_clause_name_alter_procedure_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='Document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MS.doc_type'),
        ),
    ]
