# Generated by Django 4.1.6 on 2023-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0004_alter_procedure_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='Document_type',
            new_name='document_type',
        ),
        migrations.AddField(
            model_name='procedure',
            name='document_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
