# Generated by Django 4.1.6 on 2023-02-18 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0002_alter_user_added_info_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MS', '0005_rename_document_type_procedure_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('review_on', models.DateField()),
                ('revision', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('scope', models.TextField()),
                ('review_on', models.DateField()),
                ('revision', models.IntegerField()),
                ('clause_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MS.ms_menu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_site.company')),
                ('document_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MS.doc_type')),
            ],
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='clause_name',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='company',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='document_owner',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='document_type',
        ),
        migrations.DeleteModel(
            name='Pro_details',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.AddField(
            model_name='doc_details',
            name='procedure_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MS.document'),
        ),
        migrations.AddField(
            model_name='doc_details',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
