# Generated by Django 4.1.6 on 2023-02-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0006_doc_details_doc_list_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='document_name',
        ),
    ]
