# Generated by Django 4.1.6 on 2023-02-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0007_rename_name_document_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_details',
            name='procedure_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MS.document'),
        ),
    ]
