# Generated by Django 4.1.6 on 2023-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0009_frequency_delete_doc_list_doc_details_revision_frq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approved_on',
            field=models.DateField(null=True),
        ),
    ]
