# Generated by Django 4.1.6 on 2023-02-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0013_alter_doc_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
