# Generated by Django 4.1.6 on 2023-02-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0015_document_status_alter_doc_details_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_details',
            name='status',
        ),
    ]
