# Generated by Django 4.1.6 on 2023-02-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0017_remove_document_status_doc_details_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MS_menu',
            new_name='ISO_Clauses',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MS.status'),
        ),
        migrations.AlterField(
            model_name='doc_details',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MS.status'),
        ),
    ]
