# Generated by Django 4.1.6 on 2023-02-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0004_status_process_status'),
        ('MS', '0018_rename_ms_menu_iso_clauses_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_site.process'),
        ),
    ]
