# Generated by Django 4.1.6 on 2023-02-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0019_alter_document_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_name',
        ),
    ]
