# Generated by Django 4.1.6 on 2023-02-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0004_status_process_status'),
        ('MS', '0020_remove_document_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_site.process'),
        ),
    ]
