# Generated by Django 4.1.6 on 2023-02-05 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_added_info',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_site.company'),
        ),
        migrations.AlterField(
            model_name='user_added_info',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_site.department'),
        ),
        migrations.AlterField(
            model_name='user_added_info',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_site.job_title'),
        ),
        migrations.AlterField(
            model_name='user_added_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
