# Generated by Django 4.1.6 on 2023-02-25 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0002_alter_user_added_info_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=150)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_site.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_site.department')),
            ],
        ),
    ]
