# Generated by Django 4.1.6 on 2023-02-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0005_company_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='department',
        ),
    ]
